src/Entity/Recette.php
<?php

namespace App\Entity;

use App\Repository\RecetteRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: RecetteRepository::class)]
class Recette
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $Name = null;

    #[ORM\Column(length: 500)]
    private ?string $Description = null;

    #[ORM\Column(type: Types::TIME_MUTABLE)]
    private ?\DateTimeInterface $Time = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getTime(): ?\DateTimeInterface
    {
        return $this->Time;
    }

    public function getToStringTime(): ?string
    {
        return $this->Time->format("H:i");
    }

    public function setTime(\DateTimeInterface $Time): self
    {
        $this->Time = $Time;

        return $this;
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Repository\RecetteRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class HomeController extends AbstractController
{
    #[Route('/', name: 'app_home')]
    public function index(RecetteRepository $recetteRepository): Response
    {
        $test = $this->getUser();
        $recette = $recetteRepository->findAll();

        return $this->render('home/index.html.twig', [
            'user' => $test,
            'recettes' => $recette
        ]);
    }
}

templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Home{% endblock %}

{% block body %}
    <body class="bg-gray-300 h-screen font-semibold ">
        <header class="sticky top-0 z-50">
            <div class="w-full flex justify-between py-3 bg-gray-800">
                <div class="w-1/3 text-green-700 px-3">
                    <a class="px-3" href="#">Délice de Cuisine</a>
                </div>
                <div class="bg-white  border-2 border-white rounded">
                    <form action="" method="GET">
                        <label class="p-1 font-light">
                            <input type="text" placeholder="Rechercher une recette">
                        </label>
                        <button class="px-1"><i class="fa fa-magnifying-glass"></i></button>
                    </form>
                </div>
                <div class="w-1/3 flex justify-end text-green-700 px-3">
                    {% if not is_granted('ROLE_USER')%}
                        <a class="px-3" href="{{ path('app_login') }}">Connexion</a>
                        <a class="px-3" href="{{ path('app_register') }}">Register</a>
                    {% else %}
                        <a class="px-3" href="#">{{ user }}</a>
                        <a class="px-3" href="{{ path('app_logout') }}">Deconnexion</a>
                    {% endif %}
                </div>
            </div>
        </header>

        <main class="relative h-full w-full">
            <section class=" h-1/4 flex align-middle">
                <p class="m-auto text-3xl text-green-700">Bienvenue sur mon blog recette {{ user }}</p>
            </section>

            <section class="">
                <div class="px-6">Top recette</div>
                    <div id="test" class="w-full h-full m-auto flex flex-wrap justify-evenly">
                        {%  for recette in recettes %}
                            <div class="w-1/4 h-full" {{ react_component('Card', {'name' : recette.name, 'time' : recette.toStringTime, 'desc': recette.description}) }}></div>
                        {% endfor %}
                    </div>
            </section>
        </main>
    </body>

{% endblock %}